<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CoursesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('courses')->insert([
            [
                'course_id' => 1,
                'title' => 'Introduction to Mathematics',
                'description' => 'Basic mathematics course covering algebra, geometry, and arithmetic.',
                'standard' => '10th Grade',
                'subject' => 'Mathematics',
                'teacher_id' => 1,
                'price' => 49.99,
                'thumbnail' => 'thumbnails/course-1.jpg',
                'created_at' => '2024-08-01 20:00:00',
                'updated_at' => '2024-08-01 20:00:00',
                'intro_video' => 'videos/video10.mp4',
                'course_video' => 'videos/video1.mp4',
            ],
            [
                'course_id' => 2,
                'title' => 'Advanced Physics',
                'description' => 'An in-depth course on classical mechanics, electromagnetism, and thermodynamics.',
                'standard' => '12th Grade',
                'subject' => 'Physics',
                'teacher_id' => 2,
                'price' => 79.99,
                'thumbnail' => 'thumbnails/course-2.jpg',
                'created_at' => '2024-08-01 20:10:00',
                'updated_at' => '2024-08-01 20:10:00',
                'intro_video' => 'videos/video9.mp4',
                'course_video' => 'videos/video2.mp4',
            ],
            [
                'course_id' => 3,
                'title' => 'English Literature',
                'description' => 'Exploring classical and modern English literature.',
                'standard' => '11th Grade',
                'subject' => 'English',
                'teacher_id' => 3,
                'price' => 59.99,
                'thumbnail' => 'thumbnails/course-3.jpg',
                'created_at' => '2024-08-01 20:20:00',
                'updated_at' => '2024-08-01 20:20:00',
                'intro_video' => 'videos/video8.mp4',
                'course_video' => 'videos/video3.mp4',
            ],
            [
                'course_id' => 4,
                'title' => 'World History',
                'description' => 'A comprehensive overview of world history from ancient to modern times.',
                'standard' => '10th Grade',
                'subject' => 'History',
                'teacher_id' => 4,
                'price' => 69.99,
                'thumbnail' => 'thumbnails/course-4.jpg',
                'created_at' => '2024-08-01 20:30:00',
                'updated_at' => '2024-08-01 20:30:00',
                'intro_video' => 'videos/video7.mp4',
                'course_video' => 'videos/video4.mp4',
            ],
            [
                'course_id' => 5,
                'title' => 'Chemistry Basics',
                'description' => 'Introduction to chemical principles, reactions, and laboratory techniques.',
                'standard' => '12th Grade',
                'subject' => 'Chemistry',
                'teacher_id' => 5,
                'price' => 74.99,
                'thumbnail' => 'thumbnails/course-5.jpg',
                'created_at' => '2024-08-01 20:40:00',
                'updated_at' => '2024-08-01 20:40:00',
                'intro_video' => 'videos/video6.mp4',
                'course_video' => 'videos/video5.mp4',
            ],
            [
                'course_id' => 6,
                'title' => 'Introduction to Biology',
                'description' => 'Understanding biological concepts and life sciences.',
                'standard' => '10th Grade',
                'subject' => 'Biology',
                'teacher_id' => 6,
                'price' => 54.99,
                'thumbnail' => 'thumbnails/course-6.jpg',
                'created_at' => '2024-08-01 20:50:00',
                'updated_at' => '2024-08-01 20:50:00',
                'intro_video' => 'videos/video5.mp4',
                'course_video' => 'videos/video6.mp4',
            ],
            [
                'course_id' => 7,
                'title' => 'Computer Science Fundamentals',
                'description' => 'Learning programming, data structures, and algorithms.',
                'standard' => '12th Grade',
                'subject' => 'Computer Science',
                'teacher_id' => 7,
                'price' => 89.99,
                'thumbnail' => 'thumbnails/course-7.jpg',
                'created_at' => '2024-08-01 21:00:00',
                'updated_at' => '2024-08-01 21:00:00',
                'intro_video' => 'videos/video4.mp4',
                'course_video' => 'videos/video7.mp4',
            ],
            [
                'course_id' => 8,
                'title' => 'Art and Design',
                'description' => 'Creative course focusing on drawing, painting, and design principles.',
                'standard' => '11th Grade',
                'subject' => 'Art',
                'teacher_id' => 8,
                'price' => 64.99,
                'thumbnail' => 'thumbnails/course-8.jpg',
                'created_at' => '2024-08-01 21:10:00',
                'updated_at' => '2024-08-01 21:10:00',
                'intro_video' => 'videos/video3.mp4',
                'course_video' => 'videos/video8.mp4',
            ],
            [
                'course_id' => 9,
                'title' => 'Economics 101',
                'description' => 'Introduction to microeconomics and macroeconomics.',
                'standard' => '12th Grade',
                'subject' => 'Economics',
                'teacher_id' => 9,
                'price' => 79.99,
                'thumbnail' => 'thumbnails/course-9.jpg',
                'created_at' => '2024-08-01 21:20:00',
                'updated_at' => '2024-08-01 21:20:00',
                'intro_video' => 'videos/video2.mp4',
                'course_video' => 'videos/video9.mp4',
            ],
            [
                'course_id' => 10,
                'title' => 'Physical Education',
                'description' => 'A guide to physical fitness, sports, and healthy living.',
                'standard' => '10th Grade',
                'subject' => 'Physical Education',
                'teacher_id' => 10,
                'price' => 49.99,
                'thumbnail' => 'thumbnails/course-10.jpg',
                'created_at' => '2024-08-01 21:30:00',
                'updated_at' => '2024-08-01 21:30:00',
                'intro_video' => 'videos/video1.mp4',
                'course_video' => 'videos/video10.mp4',
            ],
        ]);
    }
}
